; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 921600
lib_deps = 
	makerspaceleiden/MFRC522-spi-i2c-uart-async@^1.5.1
	adafruit/Adafruit GFX Library@^1.12.1
	adafruit/Adafruit SSD1306@^2.5.13
board_build.partitions = min_spiffs.csv
